---
title: "fin3380_quiz3"
author: "Guangyao He 118010090"
date: "2020/9/27"
output: html_document
---

# Q1
```{r}
employee = c('John Doe','Peter Gynn','Jolie Hope')
salary = c(21000, 23400, 26800)
startdate = as.Date(c('2010-11-1','2008-3-25','2007-3-14'))
employ.data = data.frame(employee, salary, startdate)
print(employ.data)
library(tibble)
as_tibble(employ.data)
```

# Q2
```{r}
employee = factor(c('John Doe','Peter Gynn','Jolie Hope'))
salary = c(21000, 23400, 26800)
startdate = as.Date(c('2010-11-1','2008-3-25','2007-3-14'))
employ.data = data.frame(employee, salary, startdate)
print(employ.data)
library(tibble)
as_tibble(employ.data)
```

# Q3
```{r}
employee = factor(c('John Doe','Peter Gynn','Jolie Hope'))
salary = c(21000, 23400, 26800)
startdate = as.Date(c('2010-11-1','2008-3-25','2007-3-14'))
employ.data1 = data.frame(employee, salary, startdate)
print(employ.data1)
library(tibble)
as_tibble(employ.data1)

employee = factor(c('John Doe','Peter Gynn','Shaun TheSheep'))
employeeid = c(123,321,1234567)
employ.data2 = data.frame(employee, employeeid)
as_tibble(employ.data2)

inner = merge(employ.data1, employ.data2, by.x = c("employee"), by.y = c("employee"), all = F)
inner

library(dplyr)
innerEmployee = employ.data1 %>% inner_join(employ.data2, by = "employee")
innerEmployee
```


